### ISSUE TITLE
Failing to install mcssa locally

### ISSUE THREAD

**Issue by khalilT** [VSainteuf/mcssa#5]
Hi, first of all, thank you for the great package !
I tried to install it like explained but I have this error message:

`ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /home/kteber/Downloads/mcssa/mcssa`

I also tried to install it directly from Github, but without sucess.
I have all the needed dependencies, and running on Python 3.9.7, could that be the problem?

**Comment by VSainteuf** [comment]
Hi @khalilT,
Can you try running `pip install -e .` in directory  `/home/kteber/Downloads/mcssa` instead of `/home/kteber/Downloads/mcssa/mcssa` ?

**Comment by khalilT** [comment]
Hi, yes it worked !
Thank you
